console.log(
    "3 of your favorite websites", 
    '\n',
    "1. https://wasongo.art/main?z=/welcome",
    '\n',
    "2. https://www.pigeonprincessart.com/",
    '\n',
    "3. https://nonkiru.art/",
    '\n',
    '\n',
    "3 of your favorite games if you play any - they can be board games, etc.",
    '\n',
    "1. Minecraft",
    '\n',
    "2. Pokemon",
    '\n',
    "3. Baldur's Gate",
    '\n',
    '\n',
    "3 of your favorite artists and their cultural importance",
    '\n',
    "1. Vincent Van Gogh, his mental health struggles and how they reflect in his paintings.",
    '\n',
    "2. Michelangelo, his religeous paintings and sculptures.",
    '\n',
    "3. Georgia O'Keeffe, helped start the Modernist Art movement",
    '\n',
    );